# This is a basic workflow to help you get started with Actions

name: Actualiza_producto_43_para_influxdb

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
    #push:
        #branches: master
        
    repository_dispatch:
      types: [update_please_from_MMA]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Actualiza_chronograf_files_p43:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: generate products from Minciencia for influx
      run: |
        cd src
        YEAR=$(date +'%Y')
        python minCiencia2Influx.py ${YEAR} $(($YEAR+1)) MP2.5
        python minCiencia2Influx.py ${YEAR} $(($YEAR+1)) MP10

    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        # Required
        commit_message: Updated influx line files

        # Optional branch to push to, defaults to the current branch
        branch: master


        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot
        commit_user_email: my-github-actions-bot@example.org
        commit_author: sebas github bot <actions@github.com>



